### ISSUE TITLE
WorldEdit and PlotMe Plugins wont work on Spigot

### ISSUE THREAD

**Issue by ofirtim** [WorldCretornica/PlotMe-Core#131]
i found this bug when i am Using the same Plugins on Spigot! Please found away to fix this shit!!!
Please!!
its happend when i Teleported to the Plotme World!

[19:14:43] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13b
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.teleport(CraftPlayer.java:484) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.teleport(CraftEntity.java:200) [Bukkit.jar:git-Spigot-1649]
	at com.worldcretornica.plotme.PMCommand.home(PMCommand.java:2190) [PlotMe%20(4).jar:?]
	at com.worldcretornica.plotme.PMCommand.onCommand(PMCommand.java:154) [PlotMe%20(4).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Bukkit.jar:git-Spigot-1649]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerTeleport(PlotWorldEditListener.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Bukkit.jar:git-Spigot-1649]
	... 21 more
[19:14:43] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to PlotMe v0.13b
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:447) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:436) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.handle(SourceFile:8) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Bukkit.jar:git-Spigot-1649]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerTeleport(PlotWorldEditListener.java:107) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Bukkit.jar:git-Spigot-1649]
	... 14 more

and this is what happend when i Entered to a Plot!

[19:14:46] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to PlotMe v0.13b
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:249) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInPosition.handle(PacketPlayInPosition.java:35) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Bukkit.jar:git-Spigot-1649]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerMove(PlotWorldEditListener.java:63) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Bukkit.jar:git-Spigot-1649]
	... 13 more
[19:14:48] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to PlotMe v0.13b
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [Bukkit.jar:git-Spigot-1649]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:249) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInFlying.a(SourceFile:137) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.PacketPlayInPosition.handle(PacketPlayInPosition.java:35) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [Bukkit.jar:git-Spigot-1649]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [Bukkit.jar:git-Spigot-1649]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.LocalSession.getMask()Lcom/sk89q/worldedit/masks/Mask;
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:61) ~[?:?]
	at com.worldcretornica.plotme.PlotWorldEdit.setMask(PlotWorldEdit.java:18) ~[?:?]
	at com.worldcretornica.plotme.listener.PlotWorldEditListener.onPlayerMove(PlotWorldEditListener.java:63) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[Bukkit.jar:git-Spigot-1649]
	... 13 more

please find away to fix my server!!! thanks!!!

**Comment by EvilOlaf** [comment]
You are using an outdated version of PlotMe. If course it wont work on 1.8.
http://www.spigotmc.org/resources/plotme.2131/

**Comment by ofirtim** [comment]
idk how to doing the new Verison!!!

**Comment by ofirtim** [comment]
and i am Using 1.7.x and 1.8.x

**Comment by EvilOlaf** [comment]
Download an place into the plugins folder. As you installed other plugins.
You can not run 1.7 and 1.8 at the same time. Therefore your statement does not make any sense.

**Comment by ofirtim** [comment]
you want my Version? its Spigot 1.7.x 1.8.x bro
i am Using right now 1.8 and my friend Using 1.7.6

**Comment by Lmmb74** [comment]
You are using the protocol hack, right?

**Comment by ofirtim** [comment]
i think yes

**Comment by EvilOlaf** [comment]
Aight "bro". Then do a reasonable statement next time by telling the exact version you are running which is visible in console at startup and in the /version command. No one has time for riddles.

Anyway as written your version of PlotMe is outdated and does not receive any further support.

**Comment by MattBDev** [comment]
This is not the place to report 0.13b bugs. 0.13b is outdated and no longer supported. We have newer versions with bug fixes. This issue is now closed.

**Comment by ZachBora** [comment]
@ofirtim You're using a plotme version that was build for worldedit 5.x but you're using worldedit 6. New plotme version will fix your problem.
