### ISSUE TITLE
/plot donelist not showing finished plots

### ISSUE THREAD

**Issue by Binary3** [WorldCretornica/PlotMe-Core#321]
Hey :)
 I just recently upgraded to newest plotme version, but now when players do /plot done, their plot isn't added to the plot donelist. Instead doing /plot donelist only returns the message "No plots are finished".
I also can't find the command on your commandlist anymore (http://plotme.worldcretornica.com/cmdsandperms), is this intentional? Or a known issue? Or is it just me having this issue?

// Binary3

**Comment by divad** [comment]
Just to confirm, you're using 0.17.4 ?

**Comment by Binary3** [comment]
checked, i run 0.16.3; thought i was on the newest. 
 Anyways, I can't actually load in 0.17.4, maybe it requires 1.8? I am on 1.7 still. Error message is further down.
Anyways, unless updating fixes my issue, its not really the important part for me, as long as donelist works, as everything else was working fine.



This is the error i get trying to load in 17.4:
[Server thread/ERROR]: Could not load 'plugins/PlotMe-Core.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:258) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
	at com.worldcretornica.plotme_core.api.event.eventbus.EventBus.<init>(EventBus.java:50) ~[?:?]
	at com.worldcretornica.plotme_core.PlotMe_Core.<init>(PlotMe_Core.java:30) ~[?:?]
	at com.worldcretornica.plotme_core.bukkit.PlotMe_CorePlugin.<init>(PlotMe_CorePlugin.java:29) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	... 6 more

**Comment by MattBDev** [comment]
plotme only supports minecraft 1.8 as of 0.17

**Comment by Binary3** [comment]
I get that. But that wasn't my issue :P My issue is that i can't get the donelsit to work on 1.6.3. Is there a fix for this?

**Comment by MattBDev** [comment]
Yes there is in 0.17 . Learn how program version works.
